### ISSUE TITLE
Repeat Start Stop of `WebSocketServer`

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/js-ws#13]
### Specification

For `js-ws`, the only thing that should be able to be repeatedly started and stopped should be `WebSocketServer`. No other classes can do this.

In order to do this properly you need to do these in a few places.

For the server stop near the end while awaiting for `this._closedP`.:

```ts
    // Wait for the socket to be closed
    await this._closedP;
    // Resets the `closedP`
    const { p: closedP, resolveP: resolveClosedP } = utils.promise();
    this._closedP = closedP;
    this.resolveClosedP = resolveClosedP;
```

For the server start right at the end before the `this.logger.info`:

```
    this._closed = false;
```

This should ensure that when stopping, you will reset the `closedP` promise. And when you start again, you have ensured that `this._closed = false`.

Right now your comments https://github.com/MatrixAI/js-ws/blob/fe32230e55e2831b12739975fda81faad9b81c3c/src/WebSocketServer.ts#L300C27-L300C27 doesn't quite make sense.

Then make sure you are testing this.

Also `this._closedP` should be used, because `closedP` should be exposed as a readonly getter. So that `this._closedP` is a protected property.

### Tasks

1. Reset the `closedP` during `WebSocketServer.stop()`.
2. Make sure that you set `this._closed = false` when you start it again.
3. Make sure you have a repeated start/stop.
4. Make sure the `closedP` is a readonly getter method.

**Comment by amydevs** [comment]
This should be resolved in the latest commit on staging

**Comment by amydevs** [comment]
if the closedP is reset on stop, won't there be a floating promise? @CMCDragonkai

**Comment by CMCDragonkai** [comment]
No, it's a tracked promise because it's a property.

**Comment by CMCDragonkai** [comment]
No promises don't keep the process open. They get gced when there's no more reference.

**Comment by CMCDragonkai** [comment]
Can you get this quick fixed and closed?

**Comment by CMCDragonkai** [comment]
Just push straight to staging, no PR required.

**Comment by CMCDragonkai** [comment]
Remember to lintfix!! And regenerate docs.

**Comment by CMCDragonkai** [comment]
@amydevs you should have to closed this within the commit.

8514cb110468b1c16d82ab3662acebfb9a77a3f1

Also remember to lintfix, you should use `chore: lintfix` or just lintfix along with the commit in the future.
